name: BackendTests

on:
  push:
    branches: ["main"]

jobs:
  mochachai:
    name: Run mocha chai tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install npm backend
        run: |
          cd src/backend
          npm install

      - name: Run Mocha
        run: |
          cd src/backend
          npm run test
